# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountBeansTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_task.Task')),
                ('num_beans', models.PositiveIntegerField(default=100)),
            ],
            bases=('django_task.task',),
        ),
        migrations.CreateModel(
            name='SendEmailTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_task.Task')),
                ('sender', models.CharField(max_length=256)),
                ('recipients', models.TextField(help_text=b'put addresses in separate rows')),
                ('subject', models.CharField(max_length=256)),
                ('message', models.TextField(blank=True)),
            ],
            bases=('django_task.task',),
        ),
    ]
