# Generated by Django 3.2 on 2021-06-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_countbeanstaskthreaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='countbeanstask',
            name='task_verbosity',
            field=models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=2),
        ),
    ]
