# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-09 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'get_latest_by': 'created_on', 'ordering': ('-created_on',), 'verbose_name': 'Task', 'verbose_name_plural': 'All Tasks'},
        ),
    ]
