# Generated by Django 2.0.1 on 2018-02-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_task', '0002_auto_20180109_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='mode',
            field=models.CharField(choices=[('UNKNOWN', 'UNKNOWN'), ('SYNC', 'SYNC'), ('ASYNC', 'ASYNC')], db_index=True, default='UNKNOWN', max_length=128, verbose_name='mode'),
        ),
    ]
