# Generated by Django 2.0.1 on 2018-02-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_task', '0003_task_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='log_text',
            field=models.TextField(default='', verbose_name='log text'),
            preserve_default=False,
        ),
    ]
