# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-16 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_task', '0004_task_log_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=256, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='log_text',
            field=models.TextField(blank=True, verbose_name='log text'),
        ),
    ]
