# Generated by Django 2.0.1 on 2018-03-27 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_task', '0005_auto_20180316_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
